[package]
name = "ckb-vm"
description = "CKB's Virtual machine"
version = "0.19.1"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
build = "build.rs"

[features]
default = []
# Require asm feature, generates an error if asm cannot be enabled.
asm = []
# Detect if requirements are met, and enable asm feature when we can.
detect-asm = []
# When chaos_initialization opened, fill the memory with random data when
# VM initializing. Note: Unless you strongly know what you are doing,
# do not open this flag because it does not meet the RISC-V convention.
chaos_initialization = ["rand"]

[dependencies]
byteorder = "1"
bytes = "0.5.4"
goblin = "0.2.0"
scroll = "0.10"
ckb-vm-definitions = { path = "definitions", version = "0.19.1" }
derive_more = "0.99.2"
rand = { version = "0.7.3", optional = true }

# Feature detection won't work here
[target.'cfg(any(windows, unix))'.dependencies]
libc = "0.2.47"
memmap = "0.7.0"

[build-dependencies]
cc = "1.0"

[dev-dependencies]
criterion = "0.3.0"
proptest = "0.9.1"

[[bench]]
name = "bits_benchmark"
harness = false

[[bench]]
name = "vm_benchmark"
harness = false
